//
//  TableViewModel.swift
//  PremierLeague
//
//  Created by epita on 07/08/2020.
//  Copyright © 2020 Juan Riveros. All rights reserved.
//

import Foundation

class TableViewModel {
    
    private var array: [Team]
    
    init() {
        
        self.array = [Team(imageTeam: "Arsenal-Team",
                           imageBadge: "Arsenal",
                           name:"Arsenal",
                           knownAs: "The Gunners",
                           coach: Person(name:"Mikel Arteta",
                                         image: "Arsenal-Mikel",
                                         age: 38,
                                         titles: 1),
                           yearBorn: 1886,
                           leagueTitles: 13,
                           stadium: "Emirates Stadium",
                           city: "London"),
                      Team(imageTeam: "Aston-Team",
                           imageBadge: "Aston Villa",
                           name:"Aston Villa",
                           knownAs: "The Villans",
                           coach: Person(name:"Dean Smith",
                                         image:"Aston-Dean",
                                         age: 49,
                                         titles: 0),
                           yearBorn: 1876,
                           leagueTitles: 7,
                           stadium: "Villa Park",
                           city: "Birmingham"),
                      Team(imageTeam: "Brighton-Team",
                           imageBadge: "Brighton",
                           name:"Brighton & Hove Albion",
                           knownAs: "The Seaguls",
                           coach: Person(name:"Graham Potter",
                                         image: "Brighton-Graham",
                                         age: 45,
                                         titles: 1),
                           yearBorn: 1901,
                           leagueTitles: 0,
                           stadium: "Falmer Stadium",
                           city: "Brighton"),
                      Team(imageTeam: "Burnley-Team",
                           imageBadge: "Burnley",
                           name:"Burnley",
                           knownAs: "The Clarets",
                           coach: Person(name:"Sean Dyche",
                                         image: "Burnley-Sean",
                                         age: 49,
                                         titles: 1),
                           yearBorn: 1882,
                           leagueTitles: 2,
                           stadium: "Turf Moor",
                           city: "Burnley"),
                      Team(imageTeam: "Chelsea-Team",
                           imageBadge: "Chelsea",
                           name:"Chelsea",
                           knownAs: "The Blues",
                           coach: Person(name:"Frank Lampard",
                                         image: "Chelsea-Lampard",
                                         age: 42,
                                         titles: 0),
                           yearBorn: 1905,
                           leagueTitles: 6,
                           stadium: "Stamford Bridge",
                           city: "London"),
                      Team(imageTeam: "Crystal-Team",
                           imageBadge: "Crystal Palace",
                           name:"Crystal Palace",
                           knownAs: "The Eagles",
                           coach: Person(name:"Roy Hodgson",
                                         image:"Crystal-Hodgson",
                                         age: 73,
                                         titles: 4),
                           yearBorn: 1905,
                           leagueTitles: 2,
                           stadium: "Selhurst Park",
                           city: "London"),
                      Team(imageTeam: "Everton-Team",
                           imageBadge: "Everton",
                           name:"Everton",
                           knownAs: "The Toffees",
                           coach: Person(name:"Carlo Ancelotti",
                                         image:"Everton-Ancelotti",
                                         age: 61,
                                         titles: 20),
                           yearBorn: 1878,
                           leagueTitles: 9,
                           stadium: "Goodison Park",
                           city: "Liverpool"),
                      Team(imageTeam: "Fulham-Team",
                           imageBadge: "Fulham",
                           name:"Fulham",
                           knownAs: "The Cottagers",
                           coach: Person(name:"Scott Parker",
                                         image: "Fulham-Parker",
                                         age: 39,
                                         titles: 0),
                           yearBorn: 1879,
                           leagueTitles: 0,
                           stadium: "Craven Cottage",
                           city: "London"),
                      Team(imageTeam: "Leeds-Team",
                           imageBadge: "Leeds",
                           name:"Leeds",
                           knownAs: "The Whites",
                           coach: Person(name:"Marcelo Bielsa",
                                         image:"Leeds-Bielsa",
                                         age: 65,
                                         titles: 6),
                           yearBorn: 1919,
                           leagueTitles: 3,
                           stadium: "Elland Road",
                           city: "Leeds"),
                      Team(imageTeam: "Leicester-Team",
                           imageBadge: "Leicester",
                           name:"Leicester",
                           knownAs: "The Foxes",
                           coach: Person(name:"Brendan Rodgers",
                                         image:"Leicester-Brendan",
                                         age: 47,
                                         titles: 7),
                           yearBorn: 1884,
                           leagueTitles: 1,
                           stadium: "King Power",
                           city: "Leicester"),
                      Team(imageTeam: "Liverpool-Team",
                           imageBadge: "Liverpool",
                           name:"Liverpool",
                           knownAs: "The Reds",
                           coach: Person(name:"Jurgen Klopp",
                                         image:"Liverpool-Klopp",
                                         age: 53,
                                         titles: 9),
                           yearBorn: 1892,
                           leagueTitles: 19,
                           stadium: "Anfield",
                           city: "Liverpool"),
                      Team(imageTeam: "MCity-Team",
                           imageBadge: "Manchester City",
                           name:"Manchester City",
                           knownAs: "The Cityzens",
                           coach: Person(name:"Pep Guardiola",
                                         image: "Manchester City-Pep",
                                         age: 49,
                                         titles: 29),
                           yearBorn: 1894,
                           leagueTitles: 6,
                           stadium: "Etihad",
                           city: "Manchester"),
                      Team(imageTeam: "MUnited-Team",
                           imageBadge: "Manchester United",
                           name:"Manchester United",
                           knownAs: "The Red Devils",
                           coach: Person(name:"Ole Solskjær",
                                         image:"Manchester United-Ole",
                                         age: 47,
                                         titles: 3),
                           yearBorn: 1878,
                           leagueTitles: 20,
                           stadium: "Old Trafford",
                           city: "Manchester"),
                      Team(imageTeam: "Newcastle-Team",
                           imageBadge: "Newcastle",
                           name:"Newcastle",
                           knownAs: "The Magpies",
                           coach: Person(name:"Steve Bruce",
                                         image:"Newcastle-Steve",
                                         age: 59,
                                         titles: 0),
                           yearBorn: 1892,
                           leagueTitles: 4,
                           stadium: "St James Park",
                           city: "Newcastle"),
                      Team(imageTeam: "Sheffield-Team",
                           imageBadge: "Sheffield",
                           name:"Sheffield United",
                           knownAs: "The Blades",
                           coach: Person(name:"Chris Wilder",
                                         image:"Sheffield-Chris",
                                         age: 52,
                                         titles: 2),
                           yearBorn: 1889,
                           leagueTitles: 1,
                           stadium: "Brammal Lane",
                           city: "Sheffield"),
                      Team(imageTeam: "Southampton-Team",
                           imageBadge: "Southampton",
                           name:"Southampton",
                           knownAs: "The Saints",
                           coach: Person(name:"Ralph Hasenhüttl",
                                         image: "Southampton-Ralph",
                                         age: 53,
                                         titles: 1),
                           yearBorn: 1885,
                           leagueTitles: 0,
                           stadium: "St Marys Stadium",
                           city: "Southampton"),
                      Team(imageTeam: "Tot-Team",
                           imageBadge: "Tottenham",
                           name:"Tottenham",
                           knownAs: "Spurs",
                           coach: Person(name:"Jose Mourinho",
                                         image:"Tot-Mou",
                                         age: 57,
                                         titles: 25),
                           yearBorn: 1882,
                           leagueTitles: 2,
                           stadium: "Tottenham Hotspur Stadium",
                           city: "London"),
                      Team(imageTeam: "WestBrom-Team",
                           imageBadge: "West Bromwich",
                           name:"West Bromwich Albion",
                           knownAs: "The Baggies",
                           coach: Person(name:"Slaven Bilic",
                                         image:"WestBrom-Slaven",
                                         age: 51,
                                         titles: 0),
                           yearBorn: 1878,
                           leagueTitles: 1,
                           stadium: "The Hawthorns",
                           city: "West Bromwich"),
                      Team(imageTeam: "WestHam-Team",
                           imageBadge: "West Ham",
                           name:"West Ham",
                           knownAs: "The Hammers",
                           coach: Person(name:"David Moyes",
                                         image:"WestHam-David",
                                         age: 57,
                                         titles: 0),
                           yearBorn: 1895,
                           leagueTitles: 0,
                           stadium: "Olympic Stadium",
                           city: "London"),
                      Team(imageTeam: "Wolves-Team",
                           imageBadge: "Wolverhampton",
                           name:"Wolverhampton",
                           knownAs: "The Wolves",
                           coach: Person(name:"Nuno Espirito Santo",
                                         image:"Wolves-Nuno",
                                         age: 46,
                                         titles: 0),
                           yearBorn: 1877,
                           leagueTitles: 3,
                           stadium: "Molineux Stadium",
                           city: "Wolverhampton")]
    }
    
    func getNumberOfRows() -> Int {
        return self.array.count
    }
    
    
    func teamAt(indexPath: IndexPath) -> Team {
        return self.array[indexPath.row]
    }
    
}
